"""
Directive Engine — ROOT's autonomous strategic executive function.

Every 15 minutes, ROOT:
1. Gathers a full system snapshot (goals, market intel, learnings, patterns, queue)
2. Synthesizes via LLM into 1-5 ranked strategic directives
3. Dispatches directives to agents via collaboration patterns
4. Records outcomes for future learning

This is what makes ROOT self-directing — it generates its own work
without waiting for Yohan.

Enhanced features:
- Impact scoring: estimated value (high/medium/low) per directive
- Conflict detection: flags directives that contradict active ones
- Rollback registry: undoes directive side-effects on failure
- Directive templates: reusable common patterns
- Approval workflow: integrates reason/benefit/risk into approval requests
- Smarter chaining: outcome-aware follow-up selection with depth scoring
- Dashboard metrics: success_rate, avg_chain_depth, value_generated
"""

from __future__ import annotations

import asyncio
import json
import logging
import sqlite3
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Optional

from backend.config import ROOT_DIR

logger = logging.getLogger("root.directive")

DIRECTIVE_DB = ROOT_DIR / "data" / "directives.db"


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


# ── Data models ──────────────────────────────────────────────────


@dataclass(frozen=True)
class Directive:
    """An autonomous strategic directive generated by ROOT."""
    id: str
    title: str
    rationale: str
    priority: int = 5  # 1=critical, 5=normal, 9=background
    category: str = "general"  # trading, learning, automation, research, health, product
    assigned_agents: tuple[str, ...] = ()
    collab_pattern: str = "delegate"  # delegate | pipeline | fanout | council
    task_description: str = ""
    status: str = "proposed"  # proposed | executing | completed | failed | expired
    result: Optional[str] = None
    source_signals: tuple[str, ...] = ()
    ttl_minutes: int = 120
    created_at: str = field(default_factory=_now_iso)
    executed_at: Optional[str] = None
    completed_at: Optional[str] = None
    # Impact scoring
    impact_score: float = 0.5          # 0.0-1.0 estimated value
    impact_label: str = "medium"       # low | medium | high | critical
    estimated_value_usd: float = 0.0   # dollar value estimate when applicable
    # Conflict tracking
    conflict_flags: tuple[str, ...] = ()   # IDs of conflicting active directives
    # Approval fields
    approval_reason: str = ""
    approval_benefit: str = ""
    approval_risk: str = ""
    # Template tracking
    template_id: Optional[str] = None     # source template if spawned from one


# ── Directive templates ───────────────────────────────────────────────

@dataclass(frozen=True)
class DirectiveTemplate:
    """A reusable directive pattern that can be instantiated on demand."""
    id: str
    name: str
    description: str
    category: str
    collab_pattern: str
    default_agents: tuple[str, ...]
    task_template: str       # May contain {variable} placeholders
    priority: int = 5
    ttl_minutes: int = 120
    impact_label: str = "medium"
    tags: tuple[str, ...] = ()


# Built-in templates for common strategic patterns
DIRECTIVE_TEMPLATES: dict[str, DirectiveTemplate] = {
    "market_scan": DirectiveTemplate(
        id="market_scan",
        name="Market Opportunity Scan",
        description="Scan market signals for actionable trading opportunities",
        category="trading",
        collab_pattern="pipeline",
        default_agents=("swarm", "analyst"),
        task_template="Analyze recent market signals and identify top 3 actionable opportunities. Context: {context}",
        priority=3,
        impact_label="high",
        tags=("trading", "revenue", "market"),
    ),
    "goal_unblock": DirectiveTemplate(
        id="goal_unblock",
        name="Stalled Goal Unblock",
        description="Research and propose actions to unblock a stalled goal",
        category="automation",
        collab_pattern="pipeline",
        default_agents=("researcher", "analyst"),
        task_template="Research and propose concrete actions to unblock: {goal_title}. Reason for stall: {stall_reason}",
        priority=3,
        impact_label="medium",
        tags=("goals", "unblock", "automation"),
    ),
    "revenue_opportunity": DirectiveTemplate(
        id="revenue_opportunity",
        name="Revenue Opportunity Assessment",
        description="Evaluate and prioritize revenue-generating opportunities",
        category="product",
        collab_pattern="council",
        default_agents=("swarm", "miro", "researcher"),
        task_template="Evaluate the top revenue opportunity in {domain}. Estimate monthly value and required effort.",
        priority=2,
        impact_label="high",
        tags=("revenue", "product", "money"),
    ),
    "capability_gap_fill": DirectiveTemplate(
        id="capability_gap_fill",
        name="Capability Gap Analysis",
        description="Identify and fill critical capability gaps",
        category="learning",
        collab_pattern="delegate",
        default_agents=("researcher",),
        task_template="Identify the most critical capability gap in {domain} and propose a learning plan.",
        priority=5,
        impact_label="medium",
        tags=("learning", "evolution", "capability"),
    ),
    "system_health_check": DirectiveTemplate(
        id="system_health_check",
        name="System Health Audit",
        description="Audit system health and surface actionable fixes",
        category="health",
        collab_pattern="delegate",
        default_agents=("guardian", "analyst"),
        task_template="Perform a health audit of {component}. Surface any issues with proposed fixes.",
        priority=4,
        impact_label="low",
        tags=("health", "reliability", "audit"),
    ),
    "experiment_proposal": DirectiveTemplate(
        id="experiment_proposal",
        name="Strategic Experiment Proposal",
        description="Propose and design a high-value experiment",
        category="research",
        collab_pattern="fanout",
        default_agents=("researcher", "analyst"),
        task_template="Design an experiment to test: {hypothesis}. Include success metrics and expected learnings.",
        priority=5,
        impact_label="medium",
        tags=("experiments", "learning", "research"),
    ),
    "automation_pipeline": DirectiveTemplate(
        id="automation_pipeline",
        name="Automation Pipeline Build",
        description="Design and implement an automation workflow",
        category="automation",
        collab_pattern="pipeline",
        default_agents=("coder", "builder"),
        task_template="Design and implement an automation pipeline for: {workflow_description}.",
        priority=4,
        impact_label="medium",
        tags=("automation", "engineering", "pipeline"),
    ),
}


# ── Agent selection mappings ──────────────────────────────────────

_CATEGORY_AGENTS: dict[str, list[str]] = {
    "trading": ["swarm", "analyst", "miro"],
    "research": ["researcher", "analyst"],
    "learning": ["researcher", "coder"],
    "automation": ["coder", "builder"],
    "product": ["coder", "analyst", "researcher"],
    "health": ["guardian", "analyst"],
    "general": ["researcher"],
}

_CATEGORY_RISK: dict[str, str] = {
    "trading": "high",
    "research": "low",
    "learning": "low",
    "automation": "medium",
    "product": "medium",
    "health": "low",
    "general": "low",
}


class DirectiveEngine:
    """ROOT's autonomous strategic decision engine.

    Gathers system-wide signals, synthesizes directives via LLM,
    dispatches to agents, and learns from outcomes.
    """

    CYCLE_INTERVAL = 900  # 15 minutes
    MAX_ACTIVE_DIRECTIVES = 3
    MAX_PER_CYCLE = 3

    def __init__(
        self,
        memory=None,
        llm=None,
        collab=None,
        bus=None,
        approval=None,
        learning=None,
        goal_engine=None,
        task_queue=None,
        user_patterns=None,
        escalation=None,
        registry=None,
        ecosystem=None,
        prediction_ledger=None,
        experience_memory=None,
    ) -> None:
        self._memory = memory
        self._llm = llm
        self._collab = collab
        self._bus = bus
        self._approval = approval
        self._learning = learning
        self._goal_engine = goal_engine
        self._task_queue = task_queue
        self._user_patterns = user_patterns
        self._escalation = escalation
        self._registry = registry
        self._ecosystem = ecosystem
        self._prediction_ledger = prediction_ledger
        self._experience_memory = experience_memory

        self._interest_engine = None  # Set via main.py
        self._sandbox_gate = None  # Set via main.py
        self._notification_engine = None  # Set via main.py
        self._conflict_detector = None  # Set via main.py
        self._outcome_registry = None  # Set via main.py — closed-loop learning
        self._conn: Optional[sqlite3.Connection] = None
        self._running = False
        self._task: Optional[asyncio.Task] = None
        self._cycle_count = 0
        self._failure_count: int = 0

    def set_interest_engine(self, engine) -> None:
        self._interest_engine = engine

    # ── Lifecycle ──────────────────────────────────────────────────

    def start(self) -> None:
        DIRECTIVE_DB.parent.mkdir(parents=True, exist_ok=True)
        self._conn = sqlite3.connect(str(DIRECTIVE_DB), check_same_thread=False)
        self._conn.row_factory = sqlite3.Row
        self._conn.execute("PRAGMA journal_mode=WAL")
        self._create_tables()
        logger.info("DirectiveEngine started (db=%s)", DIRECTIVE_DB)

    def stop(self) -> None:
        self._running = False
        if self._task:
            self._task.cancel()
        if self._conn:
            self._conn.close()
            self._conn = None

    def close(self) -> None:
        """Close the database connection."""
        if hasattr(self, '_conn') and self._conn:
            self._conn.close()

    @property
    def conn(self) -> sqlite3.Connection:
        if self._conn is None:
            raise RuntimeError("DirectiveEngine not started")
        return self._conn

    def _create_tables(self) -> None:
        self.conn.executescript("""
            CREATE TABLE IF NOT EXISTS directives (
                id TEXT PRIMARY KEY,
                title TEXT NOT NULL,
                rationale TEXT DEFAULT '',
                priority INTEGER DEFAULT 5,
                category TEXT DEFAULT 'general',
                assigned_agents TEXT DEFAULT '[]',
                collab_pattern TEXT DEFAULT 'delegate',
                task_description TEXT DEFAULT '',
                status TEXT DEFAULT 'proposed',
                result TEXT,
                source_signals TEXT DEFAULT '[]',
                ttl_minutes INTEGER DEFAULT 120,
                created_at TEXT NOT NULL,
                executed_at TEXT,
                completed_at TEXT
            );

            CREATE INDEX IF NOT EXISTS idx_dir_status ON directives(status);
            CREATE INDEX IF NOT EXISTS idx_dir_created ON directives(created_at DESC);
            CREATE INDEX IF NOT EXISTS idx_dir_category ON directives(category);
        """)

    # ── Background loop ───────────────────────────────────────────

    async def run_loop(self, interval: Optional[int] = None) -> None:
        """Background loop — generates and dispatches directives."""
        if self._running:
            return
        self._running = True
        actual_interval = interval or self.CYCLE_INTERVAL
        await asyncio.sleep(180)  # Let other systems warm up

        while self._running:
            try:
                await self.run_cycle()
                self._failure_count = 0
            except Exception as exc:
                self._failure_count = self._failure_count + 1
                logger.error("Directive engine cycle error: %s", exc)
                if self._failure_count >= 5:
                    logger.critical(
                        "Directive engine: %d consecutive failures — backing off 300s",
                        self._failure_count,
                    )
                    self._failure_count = 0
                    await asyncio.sleep(300)
                    continue
            await asyncio.sleep(actual_interval)

    # ── Core cycle ────────────────────────────────────────────────

    async def run_cycle(self) -> list[Directive]:
        """Run one directive generation cycle."""
        self._cycle_count += 1
        logger.info("Directive cycle %d starting", self._cycle_count)

        # Expire old directives
        self._expire_directives()

        # Check capacity
        active = self._get_active_count()
        if active >= self.MAX_ACTIVE_DIRECTIVES:
            logger.info("Directive cycle: %d active (max %d), skipping", active, self.MAX_ACTIVE_DIRECTIVES)
            return []

        # 1. Gather system snapshot
        snapshot = await self._gather_snapshot()

        # 2. Generate directives
        directives = await self._generate_directives(snapshot)

        # 3. Filter and deduplicate
        directives = self._filter_directives(directives)

        # 4. Dispatch
        results: list[Directive] = []
        for directive in directives[:self.MAX_PER_CYCLE]:
            outcome = await self._dispatch_directive(directive)
            results.append(outcome)

        logger.info(
            "Directive cycle %d: %d generated, %d dispatched",
            self._cycle_count, len(directives), len(results),
        )
        return results

    # ── Snapshot gathering ────────────────────────────────────────

    async def _gather_snapshot(self) -> dict[str, Any]:
        """Read-only sweep of all system state."""
        snapshot: dict[str, Any] = {"timestamp": _now_iso()}

        if self._goal_engine:
            active_goals = self._goal_engine.get_active_goals(limit=10)
            snapshot["active_goals"] = [
                {"id": g.id, "title": g.title, "progress": g.progress,
                 "category": g.category, "priority": g.priority}
                for g in active_goals
            ]
            assessment = await self._goal_engine.assess_all_goals()
            snapshot["stalled_goals"] = assessment.get("updates", [])

        if self._learning:
            snapshot["learning_insights"] = self._learning.get_insights()

        if self._user_patterns:
            snapshot["user_top_topics"] = self._user_patterns.get_top_topics(limit=5)
            snapshot["user_active_hours"] = self._user_patterns.get_active_hours()

        if self._task_queue:
            snapshot["task_queue"] = self._task_queue.stats()

        if self._memory:
            from backend.models.memory import MemoryQuery, MemoryType
            # Recent market intel
            market = self._memory.search(MemoryQuery(
                query="market trading prediction",
                memory_type=MemoryType.OBSERVATION, limit=5,
            ))
            snapshot["market_intel"] = [m.content[:200] for m in market]

            # Recent MiRo predictions
            miro = self._memory.search(MemoryQuery(
                query="MiRo prediction potentiality",
                memory_type=MemoryType.OBSERVATION, limit=3,
            ))
            snapshot["miro_predictions"] = [m.content[:200] for m in miro]

        # Recent directives (avoid repetition)
        snapshot["recent_directives"] = self._get_recent_titles(limit=10)

        if self._escalation:
            snapshot["escalation_stats"] = self._escalation.stats()

        # Ecosystem intelligence — cross-project opportunities
        if self._ecosystem:
            try:
                eco = self._ecosystem.get_ecosystem_summary()
                snapshot["ecosystem"] = {
                    "total_projects": eco.get("total_projects", 0),
                    "revenue_streams": eco.get("by_revenue_stream", {}),
                    "active_ports": eco.get("active_ports", {}),
                    "connections": eco.get("connections", 0),
                }
            except Exception as exc:
                logger.warning("Failed to fetch ecosystem data for directive snapshot: %s", exc)

        # Prediction intelligence — active forecasts for strategic planning
        if self._prediction_ledger:
            try:
                pending = self._prediction_ledger.get_pending()
                if pending:
                    snapshot["pending_predictions"] = [
                        {
                            "claim": getattr(p, "claim", str(p))[:150],
                            "confidence": getattr(p, "confidence", 0),
                            "source": getattr(p, "source", "unknown"),
                        }
                        for p in pending[:5]
                    ]
                pred_stats = self._prediction_ledger.stats()
                snapshot["prediction_accuracy"] = pred_stats.get("hit_rate", 0)
            except Exception as exc:
                logger.warning("Failed to fetch prediction data for directive snapshot: %s", exc)

        # Experience wisdom — avoid repeating past failures
        if self._experience_memory:
            try:
                failures = self._experience_memory.search_experiences(
                    "directive failure strategy", limit=3,
                )
                if failures:
                    snapshot["past_failures"] = [
                        getattr(f, "description", str(f))[:150]
                        for f in failures
                    ]
                successes = self._experience_memory.search_experiences(
                    "directive success revenue", limit=3,
                )
                if successes:
                    snapshot["past_successes"] = [
                        getattr(s, "description", str(s))[:150]
                        for s in successes
                    ]
            except Exception as exc:
                logger.warning("Failed to fetch experience data for directive snapshot: %s", exc)

        return snapshot

    # ── Directive generation ──────────────────────────────────────

    async def _generate_directives(self, snapshot: dict[str, Any]) -> list[Directive]:
        """Use LLM to generate strategic directives from system state."""
        if not self._llm:
            return self._generate_rule_based(snapshot)

        recent_titles = snapshot.get("recent_directives", [])
        prompt = (
            "You are the strategic executive function of ROOT — a self-organizing AI civilization "
            "that must survive, evolve, and generate value autonomously.\n\n"
            "Generate 1-3 strategic directives — autonomous actions the system should take NOW "
            "without waiting for Yohan-God (who only approves HIGH-risk decisions).\n\n"
            "## PRIME DIRECTIVE PRIORITIES\n"
            "1. SURVIVAL — ensure operational sustainability and revenue generation\n"
            "2. MONEY FIRST — revenue-generating actions always rank highest\n"
            "3. EVOLUTION — learn, build capabilities, expand knowledge\n"
            "4. UNBLOCK — resolve stalled goals and clear task backlogs\n"
            "5. OPTIMIZE — improve agent performance and system efficiency\n\n"
            "## ECONOMIC AWARENESS\n"
            "Think like a business ecosystem. Consider: micro-SaaS opportunities, "
            "automation services, data products, trading signals, lead generation, "
            "API tools. Every directive should consider economic impact.\n\n"
            "## SELF-EVOLUTION\n"
            "Continuously ask: What should we learn next? What capabilities are missing? "
            "What GitHub repos or frameworks could extend our abilities? "
            "What experiments would improve agent performance?\n\n"
            f"## System State\n{json.dumps(snapshot, default=str)[:3000]}\n\n"
            f"## Recent Directives (DO NOT REPEAT)\n{json.dumps(recent_titles)}\n\n"
            "## LEARN FROM HISTORY\n"
            "Review past directive outcomes below. Avoid repeating failed approaches. "
            "Build on successful patterns.\n"
            f"{self._get_directive_history_summary()}\n\n"
            "Return ONLY valid JSON:\n"
            '{"directives": [{"title": "...", "rationale": "...", "priority": 1-9, '
            '"category": "trading|research|learning|automation|product|health", '
            '"agents": ["agent_id", ...], '
            '"collab_pattern": "delegate|pipeline|fanout|council", '
            '"task": "specific task description for agents"}]}'
        )

        try:
            response = await self._llm.complete(
                system="You are ROOT's autonomous strategic planner. Return only valid JSON.",
                messages=[{"role": "user", "content": prompt}],
                model_tier="default",
                max_tokens=1500,
                method="proactive",
            )
            raw = response.strip()
            if raw.startswith("```"):
                raw = raw.split("\n", 1)[-1].rsplit("```", 1)[0].strip()

            data = json.loads(raw)
            items = data.get("directives", [])[:5]

            directives: list[Directive] = []
            for item in items:
                agents = item.get("agents", [])
                if not agents:
                    category = item.get("category", "general")
                    agents = _CATEGORY_AGENTS.get(category, ["researcher"])

                directives.append(Directive(
                    id=f"dir_{uuid.uuid4().hex[:12]}",
                    title=str(item.get("title", ""))[:200],
                    rationale=str(item.get("rationale", ""))[:500],
                    priority=int(item.get("priority", 5)),
                    category=str(item.get("category", "general")),
                    assigned_agents=tuple(str(a) for a in agents[:4]),
                    collab_pattern=str(item.get("collab_pattern", "delegate")),
                    task_description=str(item.get("task", ""))[:1000],
                ))
            return directives if directives else self._generate_rule_based(snapshot)

        except Exception as exc:
            logger.warning("LLM directive generation failed: %s", exc)
            return self._generate_rule_based(snapshot)

    def _generate_rule_based(self, snapshot: dict[str, Any]) -> list[Directive]:
        """Fallback: generate directives from rules when LLM unavailable."""
        directives: list[Directive] = []

        # Stalled goals → unblock
        stalled = snapshot.get("stalled_goals", [])
        for stall in stalled[:1]:
            directives.append(Directive(
                id=f"dir_{uuid.uuid4().hex[:12]}",
                title=f"Unblock stalled goal: {stall.get('title', 'unknown')[:80]}",
                rationale=f"Goal inactive for {stall.get('days_inactive', '?')} days",
                priority=3,
                category="automation",
                assigned_agents=("researcher", "analyst"),
                collab_pattern="pipeline",
                task_description=f"Research and propose actions to unblock: {stall.get('title', '')}",
                source_signals=("stalled_goal",),
            ))

        # Large task queue backlog → drain
        pending = snapshot.get("task_queue", {}).get("by_status", {}).get("pending", 0)
        if pending > 5:
            directives.append(Directive(
                id=f"dir_{uuid.uuid4().hex[:12]}",
                title=f"Drain task queue backlog ({pending} pending)",
                rationale="Task queue has accumulated pending tasks",
                priority=4,
                category="automation",
                assigned_agents=("coder",),
                collab_pattern="delegate",
                task_description=f"Process the {pending} pending tasks in queue",
                source_signals=("task_backlog",),
            ))

        # Market intel exists → trading opportunity scan
        market = snapshot.get("market_intel", [])
        if market:
            directives.append(Directive(
                id=f"dir_{uuid.uuid4().hex[:12]}",
                title="Evaluate trading opportunities from market intel",
                rationale="Fresh market intelligence available",
                priority=3,
                category="trading",
                assigned_agents=("swarm", "analyst"),
                collab_pattern="pipeline",
                task_description="Analyze recent market intel and identify actionable trades",
                source_signals=("market_intel",),
            ))

        return directives

    def _get_directive_history_summary(self) -> str:
        """Summarize recent directive outcomes for LLM context."""
        rows = self.conn.execute(
            "SELECT status, category, title FROM directives "
            "WHERE status IN ('completed', 'failed') "
            "ORDER BY created_at DESC LIMIT 20"
        ).fetchall()
        if not rows:
            return "No directive history yet."
        completed = sum(1 for r in rows if r["status"] == "completed")
        failed = sum(1 for r in rows if r["status"] == "failed")
        categories: dict[str, int] = {}
        for r in rows:
            categories[r["category"]] = categories.get(r["category"], 0) + 1
        top_cats = sorted(categories.items(), key=lambda x: x[1], reverse=True)[:3]
        recent_failures = [r["title"][:80] for r in rows if r["status"] == "failed"][:3]
        parts = [f"{completed} completed, {failed} failed."]
        parts.append(f"Top categories: {', '.join(f'{c}({n})' for c, n in top_cats)}.")
        if recent_failures:
            parts.append(f"Recent failures: {'; '.join(recent_failures)}.")
        return " ".join(parts)

    # ── Filtering ─────────────────────────────────────────────────

    def _filter_directives(self, directives: list[Directive]) -> list[Directive]:
        """Remove duplicates and check capacity."""
        recent = self._get_recent_titles(limit=20)
        filtered: list[Directive] = []
        for d in directives:
            # Skip if too similar to recent
            is_dup = any(
                self._text_overlap(d.title, title) > 0.5
                for title in recent
            )
            if not is_dup:
                filtered.append(d)

        return filtered

    @staticmethod
    def _text_overlap(a: str, b: str) -> float:
        words_a = set(a.lower().split())
        words_b = set(b.lower().split())
        if not words_a or not words_b:
            return 0.0
        return len(words_a & words_b) / len(words_a | words_b)

    # ── Dispatch ──────────────────────────────────────────────────

    async def _dispatch_directive(self, directive: Directive) -> Directive:
        """Route directive through approval and dispatch to agents."""
        # Store as proposed
        self._store_directive(directive)

        # Interest gate — block misaligned directives
        if self._interest_engine:
            allowed, reason = self._interest_engine.gate(
                subject=directive.title,
                context=directive.rationale,
            )
            if not allowed:
                logger.info("Directive blocked by interest gate: %s", directive.title[:80])
                # Store as filtered
                self._store_directive(Directive(
                    id=directive.id, title=directive.title, rationale=directive.rationale,
                    priority=directive.priority, category=directive.category,
                    status="filtered", result=reason,
                    created_at=directive.created_at,
                ))
                return Directive(
                    id=directive.id, title=directive.title, rationale=directive.rationale,
                    priority=directive.priority, category=directive.category,
                    status="filtered", result=reason,
                    created_at=directive.created_at,
                )

        # Conflict detection — check for contradictions with active directives
        if hasattr(self, '_conflict_detector') and self._conflict_detector:
            try:
                active_titles = self._get_recent_titles(limit=10)
                if active_titles:
                    conflicts = await self._conflict_detector.detect_conflicts(
                        new_action=directive.title + " " + directive.rationale,
                        existing_actions=active_titles,
                    )
                    if conflicts:
                        logger.warning("Conflict detected for directive '%s': %s",
                            directive.title[:50], conflicts[0].description[:100])
                        # Don't block, but add conflict info to the directive
            except Exception as e:
                logger.debug("Conflict detection error: %s", e)

        # Approval check
        risk = _CATEGORY_RISK.get(directive.category, "medium")
        if self._approval:
            from backend.core.approval_chain import ApprovalStatus
            approval = await self._approval.request_approval(
                agent_id="directive_engine",
                action=f"directive_{directive.category}",
                description=f"[{directive.priority}] {directive.title}: {directive.rationale[:100]}",
            )
            if hasattr(approval, 'status') and approval.status == ApprovalStatus.REJECTED:
                return self._update_directive(directive.id, status="failed", result="Rejected by approval chain")

        # Sandbox gate check — only gate high-risk directive categories
        # Research, learning, analysis, and strategy directives run freely
        _HIGH_RISK_CATEGORIES = frozenset({
            "trading", "deployment", "financial", "communication",
            "infrastructure", "external_action",
        })
        if (self._sandbox_gate is not None
                and directive.category in _HIGH_RISK_CATEGORIES):
            decision = self._sandbox_gate.check(
                system_id="agents_external",
                action=f"directive_{directive.category}",
                description=f"Dispatch directive: {directive.title[:100]}",
                agent_id="directive_engine",
                risk_level=risk,
            )
            if not decision.was_executed:
                return self._update_directive(
                    directive.id, status="failed",
                    result="Sandboxed — directive dispatch blocked",
                )

        # Dispatch via collaboration
        if not self._collab:
            return self._update_directive(directive.id, status="failed", result="No collaboration engine")

        self._update_directive(directive.id, status="executing", executed_at=_now_iso())

        try:
            agents = list(directive.assigned_agents)
            pattern = directive.collab_pattern
            task = directive.task_description or directive.title

            if pattern == "pipeline" and len(agents) >= 2:
                steps = [{"agent_id": a, "task": task} for a in agents]
                # Add {prev_result} to subsequent steps
                for i in range(1, len(steps)):
                    steps[i]["task"] = f"{task}\n\nContext from previous agent: {{prev_result}}"
                result = await self._collab.pipeline(
                    initiator="directive_engine",
                    goal=directive.title,
                    steps=steps,
                )
                result_text = result.final_result or "Pipeline complete"

            elif pattern == "fanout" and len(agents) >= 2:
                result = await self._collab.fanout(
                    initiator="directive_engine",
                    goal=directive.title,
                    agents=agents,
                    task=task,
                )
                result_text = result.final_result or "Fanout complete"

            elif pattern == "council" and len(agents) >= 2:
                result = await self._collab.council(
                    initiator="directive_engine",
                    question=task,
                    agents=agents,
                )
                result_text = result.final_result or "Council complete"

            else:
                # Default: delegate to first agent
                agent = agents[0] if agents else "researcher"
                result = await self._collab.delegate(
                    from_agent="directive_engine",
                    to_agent=agent,
                    task=task,
                )
                result_text = result.final_result or "Delegation complete"

            # Record outcome
            completed = self._update_directive(
                directive.id, status="completed",
                result=result_text[:2000], completed_at=_now_iso(),
            )

            # Record outcome for closed-loop learning
            if hasattr(self, '_outcome_registry') and self._outcome_registry:
                try:
                    self._outcome_registry.record(
                        action_type="directive",
                        action_id=directive.id,
                        intent=directive.title,
                        result=str(result_text or "")[:500],
                        quality_score=0.8 if result_text and len(str(result_text)) > 100 else 0.5,
                        context={"category": directive.category, "priority": directive.priority},
                    )
                except Exception:
                    logger.debug("Failed to record successful directive outcome for '%s'", directive.id, exc_info=True)
            # Directive chaining: create follow-up if result suggests one
            chain_keywords = ("further", "next step", "follow up", "investigate more", "deeper analysis")
            current_depth = self._get_chain_depth(directive)
            if current_depth < 3 and any(kw in result_text.lower() for kw in chain_keywords):
                follow_up = Directive(
                    id=f"dir_{uuid.uuid4().hex[:12]}",
                    title=f"Follow-up: {directive.title[:80]}",
                    rationale=f"Auto-chained from {directive.id}: {result_text[:200]}",
                    priority=min(directive.priority + 1, 9),
                    category=directive.category,
                    assigned_agents=directive.assigned_agents,
                    collab_pattern=directive.collab_pattern,
                    task_description=f"Continue from previous result: {result_text[:500]}",
                    source_signals=(*directive.source_signals, f"chain_depth:{current_depth + 1}"),
                )
                self._store_directive(follow_up)
                logger.info("Chained follow-up directive %s (depth %d)", follow_up.id, current_depth + 1)

            # Store learning
            if self._memory:
                from backend.models.memory import MemoryEntry, MemoryType
                self._memory.store(MemoryEntry(
                    content=f"Directive [{directive.category}]: {directive.title} → {result_text[:300]}",
                    memory_type=MemoryType.LEARNING,
                    tags=["directive", directive.category, "autonomous"],
                    source="directive_engine",
                    confidence=0.75,
                ))

            # Record to learning engine
            if self._learning:
                self._learning.record_agent_outcome(
                    agent_id="directive_engine",
                    task_description=f"directive:{directive.title[:100]}",
                    status="completed",
                    result_quality=0.7,
                    task_category=directive.category,
                )

            # Publish to bus
            if self._bus:
                msg = self._bus.create_message(
                    topic="system.directive",
                    sender="directive_engine",
                    payload={
                        "type": "directive_completed",
                        "directive_id": directive.id,
                        "title": directive.title,
                        "category": directive.category,
                        "result": result_text[:500],
                        "from_agent": "directive_engine",
                        "to_agent": directive.assigned_agents[0] if directive.assigned_agents else "astra",
                    },
                )
                await self._bus.publish(msg)

            return completed

        except Exception as exc:
            logger.error("Directive dispatch failed: %s", exc)
            # Record failed outcome for closed-loop learning
            if hasattr(self, '_outcome_registry') and self._outcome_registry:
                try:
                    self._outcome_registry.record(
                        action_type="directive",
                        action_id=directive.id,
                        intent=directive.title,
                        result=str(exc)[:500],
                        quality_score=0.1,
                        context={"category": directive.category, "priority": directive.priority},
                    )
                except Exception:
                    logger.debug("Failed to record failed directive outcome for '%s'", directive.id, exc_info=True)
            return self._update_directive(
                directive.id, status="failed", result=str(exc)[:500],
            )

    # ── Persistence ───────────────────────────────────────────────

    def _store_directive(self, d: Directive) -> None:
        self.conn.execute(
            """INSERT OR IGNORE INTO directives
               (id, title, rationale, priority, category, assigned_agents,
                collab_pattern, task_description, status, source_signals,
                ttl_minutes, created_at)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
            (d.id, d.title, d.rationale, d.priority, d.category,
             json.dumps(list(d.assigned_agents)), d.collab_pattern,
             d.task_description, d.status, json.dumps(list(d.source_signals)),
             d.ttl_minutes, d.created_at),
        )
        self.conn.commit()

    _DIRECTIVE_ALLOWED_COLUMNS = frozenset({
        "title", "rationale", "priority", "category", "assigned_agents",
        "collab_pattern", "task_description", "status", "result",
        "source_signals", "ttl_minutes", "executed_at", "completed_at",
    })

    def _update_directive(self, directive_id: str, **updates) -> Directive:
        """Update directive fields and return fresh copy."""
        validated = {
            k: v for k, v in updates.items()
            if k in self._DIRECTIVE_ALLOWED_COLUMNS
        }
        if not validated:
            return self._get_directive(directive_id)
        sets = ", ".join(f"{k} = ?" for k in validated)
        vals = list(validated.values()) + [directive_id]
        self.conn.execute(f"UPDATE directives SET {sets} WHERE id = ?", vals)
        self.conn.commit()
        return self._get_directive(directive_id)

    def _get_directive(self, directive_id: str) -> Directive:
        row = self.conn.execute(
            "SELECT * FROM directives WHERE id = ?", (directive_id,)
        ).fetchone()
        return self._row_to_directive(row) if row else Directive(
            id=directive_id, title="unknown", rationale="", status="failed",
        )

    def _expire_directives(self) -> int:
        """Mark old proposed/executing directives as expired."""
        now = datetime.now(timezone.utc)
        rows = self.conn.execute(
            "SELECT id, created_at, ttl_minutes FROM directives WHERE status IN ('proposed', 'executing')"
        ).fetchall()
        expired = 0
        for r in rows:
            try:
                created = datetime.fromisoformat(r["created_at"])
                if (now - created).total_seconds() > r["ttl_minutes"] * 60:
                    self.conn.execute(
                        "UPDATE directives SET status = 'expired' WHERE id = ?", (r["id"],),
                    )
                    expired += 1
            except (ValueError, TypeError):
                logger.debug("Failed to parse created_at for directive expiration check", exc_info=True)
        if expired:
            self.conn.commit()
        return expired

    def _get_active_count(self) -> int:
        return self.conn.execute(
            "SELECT COUNT(*) as c FROM directives WHERE status IN ('proposed', 'executing')"
        ).fetchone()["c"]

    def _get_recent_titles(self, limit: int = 10) -> list[str]:
        rows = self.conn.execute(
            "SELECT title FROM directives ORDER BY created_at DESC LIMIT ?", (limit,),
        ).fetchall()
        return [r["title"] for r in rows]

    # ── Queries ───────────────────────────────────────────────────

    def get_active_directives(self) -> list[dict[str, Any]]:
        rows = self.conn.execute(
            "SELECT * FROM directives WHERE status IN ('proposed', 'executing') ORDER BY priority ASC"
        ).fetchall()
        return [self._row_to_dict(r) for r in rows]

    def get_history(self, limit: int = 50) -> list[dict[str, Any]]:
        rows = self.conn.execute(
            "SELECT * FROM directives ORDER BY created_at DESC LIMIT ?", (limit,),
        ).fetchall()
        return [self._row_to_dict(r) for r in rows]

    def stats(self) -> dict[str, Any]:
        total = self.conn.execute("SELECT COUNT(*) as c FROM directives").fetchone()["c"]
        completed = self.conn.execute(
            "SELECT COUNT(*) as c FROM directives WHERE status = 'completed'"
        ).fetchone()["c"]
        failed = self.conn.execute(
            "SELECT COUNT(*) as c FROM directives WHERE status = 'failed'"
        ).fetchone()["c"]

        cat_rows = self.conn.execute(
            "SELECT category, COUNT(*) as cnt FROM directives GROUP BY category"
        ).fetchall()

        return {
            "cycles": self._cycle_count,
            "total_directives": total,
            "completed": completed,
            "failed": failed,
            "active": self._get_active_count(),
            "success_rate": round(completed / max(total, 1), 3),
            "by_category": {r["category"]: r["cnt"] for r in cat_rows},
        }

    @staticmethod
    def _get_chain_depth(directive: Directive) -> int:
        """Extract chain depth from source_signals, default 0."""
        for signal in directive.source_signals:
            if signal.startswith("chain_depth:"):
                try:
                    return int(signal.split(":")[1])
                except (ValueError, IndexError):
                    logger.debug("Failed to parse chain_depth from directive source_signals", exc_info=True)
        return 0

    # ── Helpers ───────────────────────────────────────────────────

    def _row_to_dict(self, row: sqlite3.Row) -> dict[str, Any]:
        return {
            "id": row["id"], "title": row["title"],
            "rationale": row["rationale"], "priority": row["priority"],
            "category": row["category"],
            "assigned_agents": json.loads(row["assigned_agents"] or "[]"),
            "collab_pattern": row["collab_pattern"],
            "task_description": row["task_description"],
            "status": row["status"], "result": row["result"],
            "created_at": row["created_at"],
            "executed_at": row["executed_at"],
            "completed_at": row["completed_at"],
        }

    def _row_to_directive(self, row: sqlite3.Row) -> Directive:
        return Directive(
            id=row["id"], title=row["title"],
            rationale=row["rationale"] or "",
            priority=row["priority"], category=row["category"] or "general",
            assigned_agents=tuple(json.loads(row["assigned_agents"] or "[]")),
            collab_pattern=row["collab_pattern"] or "delegate",
            task_description=row["task_description"] or "",
            status=row["status"], result=row["result"],
            source_signals=tuple(json.loads(row["source_signals"] or "[]")),
            ttl_minutes=row["ttl_minutes"] or 120,
            created_at=row["created_at"],
            executed_at=row["executed_at"],
            completed_at=row["completed_at"],
        )
