"""Conversation routes — persistent chat history across sessions."""

from __future__ import annotations
import dataclasses
import logging

from fastapi import APIRouter, HTTPException, Query, Request
from pydantic import BaseModel
from typing import Optional

logger = logging.getLogger("root.routes.conversations")


class TitleRequest(BaseModel):
    first_message: Optional[str] = None

router = APIRouter(prefix="/api/conversations", tags=["conversations"])


@router.get("/sessions")
async def list_sessions(request: Request, limit: int = Query(default=20, ge=1, le=500)):
    """List recent conversation sessions."""
    store = getattr(request.app.state, "conversations", None)
    if not store:
        return []
    return store.get_sessions(limit)


@router.get("/sessions/{session_id}")
async def get_session(session_id: str, request: Request, limit: int = Query(default=100, ge=1, le=500)):
    """Get messages from a specific session."""
    store = getattr(request.app.state, "conversations", None)
    if not store:
        return {"messages": []}
    return {"messages": store.get_session_messages(session_id, limit)}


@router.post("/sessions/new")
async def new_session(request: Request):
    """Start a new conversation session."""
    store = getattr(request.app.state, "conversations", None)
    if not store:
        raise HTTPException(status_code=503, detail="Conversations not initialized")
    session_id = store.new_session()
    return {"session_id": session_id}


@router.get("/search")
async def search_conversations(request: Request, q: str = "", limit: int = Query(default=20, ge=1, le=500)):
    """Search across all conversation messages."""
    store = getattr(request.app.state, "conversations", None)
    if not store or not q:
        return []
    return store.search_conversations(q, limit)


@router.post("/sessions/{session_id}/title")
async def generate_session_title(session_id: str, req: TitleRequest, request: Request):
    """Generate a human-readable title for a session using the first message."""
    store = getattr(request.app.state, "conversations", None)
    if not store:
        raise HTTPException(status_code=503, detail="Conversations not initialized")

    first_msg = (req.first_message or "").strip()
    if not first_msg:
        return {"title": "", "session_id": session_id}

    # Generate a concise title using Haiku (fast, cheap)
    llm = getattr(request.app.state, "llm_router", None)
    title = first_msg[:60]  # Fallback: truncate the message
    if llm:
        try:
            prompt = f"Generate a short, descriptive title (max 8 words) for a chat that starts with:\n\"{first_msg[:200]}\"\n\nReturn only the title, no quotes."
            result = await llm.chat(
                [{"role": "user", "content": prompt}],
                model_tier="fast", temperature=0.3, max_tokens=30,
            )
            if result:
                title = result.strip().strip('"\'').strip()[:80]
        except Exception as exc:
            logger.warning("Title generation failed: %s", exc)

    # Persist the title
    try:
        with store.conn:
            store.conn.execute(
                "UPDATE sessions SET title = ? WHERE id = ?",
                (title, session_id),
            )
    except Exception as exc:
        logger.warning("Failed to save session title: %s", exc)

    return {"title": title, "session_id": session_id}


@router.get("/stats")
async def conversation_stats(request: Request):
    store = getattr(request.app.state, "conversations", None)
    if not store:
        return {"total_sessions": 0, "total_messages": 0}
    return store.stats()


@router.get("/digest/latest")
async def get_latest_digest(request: Request, digest_type: str = "daily"):
    """Get the latest digest (daily/weekly) generated by the digest engine."""
    digest_engine = getattr(request.app.state, "digest", None)
    if not digest_engine:
        return {"digest": None}
    digest = digest_engine.get_latest(digest_type)
    return {"digest": dataclasses.asdict(digest) if digest else None}


@router.post("/digest/generate")
async def generate_digest(request: Request, digest_type: str = "daily"):
    """Trigger on-demand digest generation."""
    digest_engine = getattr(request.app.state, "digest", None)
    if not digest_engine:
        raise HTTPException(status_code=503, detail="Digest engine not available")
    if digest_type == "weekly":
        digest = await digest_engine.generate_weekly()
    else:
        digest = await digest_engine.generate_daily()
    return {"digest": dataclasses.asdict(digest)}
